name: Test action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: windows-latest
   
    steps:
      - name: Checkout code
        id: step1
        uses: actions/checkout@v2

      - name: Send mail
        if: steps.step1.outputs.status == 'failure'
        uses: ./
      
