name: Test action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: windows-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - content_type: text/markdown
            attachments: action.yml
            body: file://README.md
          - content_type: text/html
            attachments: package.json,package-lock.json
            body: |
              <!DOCTYPE html>
              <html>
              <body>
              <h1>Heading</h1>
              <p>Paragraph</p>
              </body>
              </html>
          - content_type: text/html
            convert_markdown: true
            body: |
              # h1
              ## h2
              ### h3
              **bold**
              _italics_
              - bullet 1
              - bullet 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send mail
        uses: ./
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: iamajaysingla001@gmail.com
          password: appwrk@@
          subject: Email Notification from CI-CD
          body: ${{matrix.body}}
          to: audry.s@appwrk.com
          from: iamajaysingla001@gmail.com
          content_type: ${{matrix.content_type}}
          convert_markdown: ${{matrix.convert_markdown}}
          attachments: ${{matrix.attachments}}
