name: Test action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: windows-latest
   
    steps:
      - name: Checkout code
        id: step1
        uses: actions/checkout@v2
        continue-on-error: true

      - name: Send mail
        if: ${{(steps.step1.outcome !== 'failure') }}
        uses: ./
      
