name: Test action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: windows-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send mail
        uses: ./
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: iamajaysingla001@gmail.com
          password: appwrk@@
          subject: Email Notification from CI-CD-1
          body: ${{matrix.body}}
          to: audry.s@appwrk.com
          from: iamajaysingla001@gmail.com
          content_type: ${{matrix.content_type}}
          convert_markdown: ${{matrix.convert_markdown}}
          attachments: ${{matrix.attachments}}
