name: Test action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: windows-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - content_type: text/markdown
            attachments: action.yml
            body: file://README.md
          - content_type: text/html
            attachments: package.json,package-lock.json
            body: |
              <!DOCTYPE html>
              <html>
              <body>
              <h1>Heading</h1>
              <p>Paragraph</p>
              </body>
              </html>
          - content_type: text/html
            convert_markdown: true
            body: |
              # h1
              ## h2
              ### h3
              **bold**
              _italics_
              - bullet 1
              - bullet 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send mail
        uses: ./
        with:
          server_address: email-smtp.us-east-1.amazonaws.com
          server_port: 587
          username: AKIA2MOZ7C2ARTAOIIVZ
          password: BAJgYXdTGG2DoUKEffOoxhiUSIWe5nq9uM9W7oxWaM9E
          subject: Email Notification from CI-CD
          body: ${{matrix.body}}
          to: ${{github.event.pusher.email}}
          from: direct@spincv.com
          content_type: ${{matrix.content_type}}
          convert_markdown: ${{matrix.convert_markdown}}
          attachments: ${{matrix.attachments}}
